apiVersion: v1
kind: Service
metadata:
  name: kubernates-demo-api-api-service
spec:
  type: NodePort
  selector:
    app: kubernates-demo-api-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
  type: NodePort